### ISSUE TITLE
Can't urn ridden wolves back to normal ones.

### ISSUE THREAD

**Issue by InflamedSebi** [BillyGalbreath/Ridables#3]
Once i took a ride with my wolf, it refuses to follow me like a normal wolf.
Also I can not make him sit again. He is just standing there staring at a wall.

**Comment by BillyGalbreath** [comment]
Give it a few moments and he will start following you again and responding to sit/stand clicks.

I have a feeling this one is because while riding I force the entities to untarget everything. Targeting take a few moments to trigger again once unmounted.

I'll look into it deeper to find a better solution.

**Comment by InflamedSebi** [comment]
Well ...  that one wolf is still not responding. Even server restart did not fix this.

**Comment by BillyGalbreath** [comment]
Ok, found the cause of the bug. It's another bug in Spigot/CraftBukkit. Leaving this open until md_5 can get it fixed cause there's nothing I can do.

https://hub.spigotmc.org/jira/browse/SPIGOT-4240

**Comment by BillyGalbreath** [comment]
Same for this. I found a workaround fix while talking to md_5 about the initial bug.
