### ISSUE TITLE
Is there any downside to enabling enable-move-event?

### ISSUE THREAD

**Issue by mibby** [BillyGalbreath/Ridables#38]
I could not find ``enable-move-event`` referenced anywhere in the wiki and noticed it was disabled by default. Is there any pros or cons to having it one way over the other?

**Comment by BillyGalbreath** [comment]
It has the same potential to lag the same as a player moving.

If you have a plug-in that needs to track players movement (like worldguard for the enter/exit flags, etc) then you should enable it. If you don't need it then it's better to have it disabled.

The only thing enabling that option does is [fire PlayerMoveEvent](https://github.com/BillyGalbreath/Ridables/blob/v3.0/src/main/java/net/pl3x/bukkit/ridables/entity/RidableEntity.java#L90-L117) when a ridable moves because a rider told it to (wasd)

**Comment by mibby** [comment]
Okay, thanks for the info! Fortunately I do rely on plugins like WorldGuard to flag players when they enter a region, so I suppose I'll have to keep it enabled.
